name: CI
on:
  pull_request:
    paths-ignore:
    - doc/**
    - README.md
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        #- macos-latest
        #- windows-latest
        python-version:
        - '3.11'
        #- '3.13'
        sync-args:
        - ''
        include:
        - os: ubuntu-22.04
          python-version: 3.10.0
          sync-args: --resolution=lowest-direct

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout Source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Setup uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: uv sync --no-editable --group test ${{ matrix.sync-args }}
    - name: Run tests
      run: |
        uv run --no-sync pytest --color=yes
        uv run --no-sync coverage xml -o coverage.xml
        uv run --no-sync coverage report -m
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ matrix.python-version }}
        path: coverage.xml
    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        flags: unittests
        name: codecov-report
  type-check:
    runs-on: ubuntu-latest
    name: type check

    concurrency:
      group: ${{ github.ref }}-dev
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0

    - name: Setup uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
      with:
        # Match minimal supported Python version
        # to make sure we're not using unparseable syntax
        python-version: '3.10'

    - name: Run mypy
      run: uv run --group typecheck mypy src
